### ISSUE TITLE
[BUG] Typo in failed to login notification message

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sn-client#204]
# 🐜 Bug Report

Typo in failed to login notification message.

## 📦 Package / Application

sn-app

## 📃 Version

0.2.0
## 🐜 Describe the bug

An apostrophe is missing after the username in the notification message that is displayed after failed login attempts:

```Failed to log in with user 'businesscat@sensenet.com to repository 'https://devservice.demo.sensenet.com```

## 👉 Steps To Reproduce

1. Reproduce a failed login (eg. wrong password) to a repo.
1. Check notification error message

## 😯 Current behavior

Apostrophe missing. Immediate disappointment ensues, followed by permanent despair.

## 🤔 Expected behavior

The apostrophe should not be missing. This world needs more apostrophes!!

## 🖼 Screenshots

![image](https://user-images.githubusercontent.com/39081660/58077222-56a8b880-7bac-11e9-8ad4-e605007e2c8b.png)

## 🌍 Your Environment (for developers)

| Software         | Version(s) |
| ---------------- | ---------- |
| Language (js/ts) |
| Operating System |
| NPM/Node/Yarn    |
| Bundler          |

## 🌍 Your environment (for apps / examples)

- Device: laptop
  
- OS: Windows 10
  
- Browser: Chrome
  
- Version: 74.0.3729.157 (Official Build) (64-bit)

**Comment by gallayl** [comment]
fixed in the referenced PR

**Comment by kultsar** [comment]
Apostrophe still missing after username in login notification message for me when logging in at https://5cebd0a75ff1ede070194da2--sn-app-dev.netlify.com

**Comment by gallayl** [comment]
![image](https://user-images.githubusercontent.com/16716099/58476879-60a15d00-8152-11e9-91ce-8744ebea81fc.png)

**Comment by kultsar** [comment]
My bad, mixed up with successful login message.
